name = "Pathfinding"
version = "0.1.0"
testRunner = "Test"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Pathfinding"

[[lean_lib]]
name = "Test"
